# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_path <- function(X_list, censoring_list, B, rankmin_list, rankmax_list, step_size, lambda_1_all, lambda_2_all, penalty_factor, niter, linesearch_beta, eps, tol = 1e-10) {
    .Call(`_proxgpu_solve_path`, X_list, censoring_list, B, rankmin_list, rankmax_list, step_size, lambda_1_all, lambda_2_all, penalty_factor, niter, linesearch_beta, eps, tol)
}

